#!/bin/bash

#http://www.patorjk.com/software/taag/#p=display&f=Bubble&t=module_auth
splash_bubble() {
echo "   _   _   _   _   _   _   _   _   _   _   _  "
echo "  / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ / \ "
echo " ( m | o | d | u | l | e | _ | a | u | t | h )"
echo "  \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ "
}

splash() {
  echo ""
  splash_bubble
  echo ""
}

HOHENHEIM_HOME=@@HHH_HOME@@
APPDIR=@@APP_DIR@@
CWD=`pwd`

if [ "$JAVA_HOME" = "" ] ; then
  echo "Attempt to reference standard java location on system: /usr/bin."
  #echo "Please set JAVA_HOME"
  #exit -1
  JAVA_HOME=/usr
fi

PATCHDIR=$HOHENHEIM_HOME/patch/*
DISTRO=$HOHENHEIM_HOME/dist/*
LIBDIR=$HOHENHEIM_HOME/lib/*
BCP=$PATCHDIR:$DISTRO:$LIBDIR:$APPDIR/POD-INF/classes:$APPDIR/POD-INF/patch/*:$APPDIR/POD-INF/lib/*:$CLASSPATH

JAVA_CMD=$JAVA_HOME/bin/java

VMXRGS=" -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:MaxPermSize=256m"
MAINCZ=comzotohcljc.hhh.auth.core
VMARGS="-Xms512m -Xmx7096m $VMXRGS"
LOG4J=etc/log/logback.xml
L4JFILE=${HOHENHEIM_HOME}/$LOG4J
L4J=file:${L4JFILE}
LOGCFG=$L4J
LOGREF="-Dlogback.configurationFile=$LOGCFG"
if [ ! -e ${L4JFILE} ]; then
    LOGREF=
fi

splash
$JAVA_CMD $VMARGS -cp $BCP $LOGREF $MAINCZ $APPDIR $@
cd $CWD
exit 0




